# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.category import Category  # noqa: F401,E501
from swagger_server.models.tag import Tag  # noqa: F401,E501
from swagger_server import util


class Notification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, category: Category=None, photo_urls: List[str]=None, tags: List[Tag]=None, status: str=None):  # noqa: E501
        """Notification - a model defined in Swagger

        :param id: The id of this Notification.  # noqa: E501
        :type id: int
        :param name: The name of this Notification.  # noqa: E501
        :type name: str
        :param category: The category of this Notification.  # noqa: E501
        :type category: Category
        :param photo_urls: The photo_urls of this Notification.  # noqa: E501
        :type photo_urls: List[str]
        :param tags: The tags of this Notification.  # noqa: E501
        :type tags: List[Tag]
        :param status: The status of this Notification.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'category': Category,
            'photo_urls': List[str],
            'tags': List[Tag],
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'category': 'category',
            'photo_urls': 'photoUrls',
            'tags': 'tags',
            'status': 'status'
        }
        self._id = id
        self._name = name
        self._category = category
        self._photo_urls = photo_urls
        self._tags = tags
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Notification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Notification of this Notification.  # noqa: E501
        :rtype: Notification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Notification.


        :return: The id of this Notification.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Notification.


        :param id: The id of this Notification.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Notification.


        :return: The name of this Notification.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Notification.


        :param name: The name of this Notification.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def category(self) -> Category:
        """Gets the category of this Notification.


        :return: The category of this Notification.
        :rtype: Category
        """
        return self._category

    @category.setter
    def category(self, category: Category):
        """Sets the category of this Notification.


        :param category: The category of this Notification.
        :type category: Category
        """

        self._category = category

    @property
    def photo_urls(self) -> List[str]:
        """Gets the photo_urls of this Notification.


        :return: The photo_urls of this Notification.
        :rtype: List[str]
        """
        return self._photo_urls

    @photo_urls.setter
    def photo_urls(self, photo_urls: List[str]):
        """Sets the photo_urls of this Notification.


        :param photo_urls: The photo_urls of this Notification.
        :type photo_urls: List[str]
        """
        if photo_urls is None:
            raise ValueError("Invalid value for `photo_urls`, must not be `None`")  # noqa: E501

        self._photo_urls = photo_urls

    @property
    def tags(self) -> List[Tag]:
        """Gets the tags of this Notification.


        :return: The tags of this Notification.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[Tag]):
        """Sets the tags of this Notification.


        :param tags: The tags of this Notification.
        :type tags: List[Tag]
        """

        self._tags = tags

    @property
    def status(self) -> str:
        """Gets the status of this Notification.

        notification status in the store  # noqa: E501

        :return: The status of this Notification.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Notification.

        notification status in the store  # noqa: E501

        :param status: The status of this Notification.
        :type status: str
        """
        allowed_values = ["available", "pending", "sold"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
