openapi: 3.0.3
info:
  title: Swagger Notification - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: arauzk@globalhitss.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080/rest/notification-api/v1.0
tags:
- name: push
  description: Everything about your Notifications
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /update:
    post:
      tags:
      - push
      summary: Add a new notification to the store
      description: Add a new notification to the store
      operationId: add_notification
      requestBody:
        description: Create a new notification in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.push_controller
  /notification/findByStatus:
    get:
      tags:
      - push
      summary: Finds Notifications by status
      description: Multiple status values can be provided with comma separated strings
      operationId: find_notifications_by_status
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: available
          enum:
          - available
          - pending
          - sold
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        "400":
          description: Invalid status value
      x-openapi-router-controller: swagger_server.controllers.push_controller
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
      example:
        name: Dogs
        id: 1
      xml:
        name: category
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        name: name
        id: 6
      xml:
        name: tag
    Notification:
      required:
      - name
      - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: notification status in the store
          enum:
          - available
          - pending
          - sold
      example:
        photoUrls:
        - photoUrls
        - photoUrls
        name: doggie
        id: 0
        category:
          name: Dogs
          id: 1
        tags:
        - name: name
          id: 6
        - name: name
          id: 6
        status: available
      xml:
        name: notification

